id: AttackIQ - Test
version: -1
name: AttackIQ - Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e1cbdd48-28a5-4ccf-8d88-169663cf97d4
    type: start
    task:
      id: e1cbdd48-28a5-4ccf-8d88-169663cf97d4
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: bc8e241a-daea-4777-86ba-ed5a7e4e142d
    type: regular
    task:
      id: bc8e241a-daea-4777-86ba-ed5a7e4e142d
      version: -1
      name: Clear Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 2e8a4b36-227c-4a3a-8df1-98297eb58eee
    type: regular
    task:
      id: 2e8a4b36-227c-4a3a-8df1-98297eb58eee
      version: -1
      name: Activate assessment
      description: Activates the assessment. this is required for execution.
      script: '|||attackiq-activate-assessment'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      assessment_id:
        simple: c4e352ae-1506-4c74-bd90-853f02dd765a
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 6aa03fd5-f7fe-4667-8a92-2df54b8d64eb
    type: regular
    task:
      id: 6aa03fd5-f7fe-4667-8a92-2df54b8d64eb
      version: -1
      name: Get assessment execution status
      description: Get assessment execution status - supports only on demand runs.
      script: '|||attackiq-get-assessment-execution-status'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      assessment_id:
        simple: c4e352ae-1506-4c74-bd90-853f02dd765a
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: c49743e8-781c-42af-8463-be9ca4c0b10f
    type: condition
    task:
      id: c49743e8-781c-42af-8463-be9ca4c0b10f
      version: -1
      name: Assert execution status
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isFalse
          left:
            value:
              simple: AttackIQ.Assessment.Running
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: b1a1f498-a32f-44c6-8810-3dc7fb51e095
    type: regular
    task:
      id: b1a1f498-a32f-44c6-8810-3dc7fb51e095
      version: -1
      name: Get test execution status
      description: Get test run status.
      script: '|||attackiq-get-test-execution-status'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      test_id:
        simple: 1c350a5a-84f2-4938-93d8-cc31f0a99482
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 22691038-0f0f-476c-8bb3-0796810a9175
    type: condition
    task:
      id: 22691038-0f0f-476c-8bb3-0796810a9175
      version: -1
      name: Assert test execution status
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              simple: AttackIQ.Test.Detected
            iscontext: true
          right:
            value:
              simple: "0"
      - - operator: isEqualNumber
          left:
            value:
              simple: AttackIQ.Test.Failed
            iscontext: true
          right:
            value:
              simple: "2"
      - - operator: isTrue
          left:
            value:
              simple: AttackIQ.Test.Finished
            iscontext: true
      - - operator: isEqualNumber
          left:
            value:
              simple: AttackIQ.Test.Passed
            iscontext: true
          right:
            value:
              simple: "49"
      - - operator: isEqualNumber
          left:
            value:
              simple: AttackIQ.Test.Errored
            iscontext: true
          right:
            value:
              simple: "0"
      - - operator: isEqualNumber
          left:
            value:
              simple: AttackIQ.Test.Total
            iscontext: true
          right:
            value:
              simple: "51"
      - - operator: isEqualString
          left:
            value:
              simple: AttackIQ.Test.Id
            iscontext: true
          right:
            value:
              simple: 1c350a5a-84f2-4938-93d8-cc31f0a99482
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: 4594945e-2a35-433a-8c6a-8a3b00af57a8
    type: regular
    task:
      id: 4594945e-2a35-433a-8c6a-8a3b00af57a8
      version: -1
      name: Get test results
      script: '|||attackiq-get-test-results'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      show_last_result:
        simple: "True"
      test_id:
        simple: 1c350a5a-84f2-4938-93d8-cc31f0a99482
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1250
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 5862747c-718c-4a0b-8bbe-334d97e5c28a
    type: condition
    task:
      id: 5862747c-718c-4a0b-8bbe-334d97e5c28a
      version: -1
      name: Assert test results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: AttackIQ.TestResult.Id
            iscontext: true
          right:
            value:
              simple: 9ba7abd8-dd01-4f29-9c0c-c4a035f86870
      - - operator: isEqualString
          left:
            value:
              simple: AttackIQ.TestResult.Modified
            iscontext: true
          right:
            value:
              simple: 2019-09-03T14:23:49.769485Z
      - - operator: isEmpty
          left:
            value:
              simple: AttackIQ.TestResult.RunCount
            iscontext: true
      - - operator: isEqualString
          left:
            value:
              simple: AttackIQ.TestResult.Project.Id
            iscontext: true
          right:
            value:
              simple: c4e352ae-1506-4c74-bd90-853f02dd765a
      - - operator: isEqualString
          left:
            value:
              simple: AttackIQ.TestResult.Project.Name
            iscontext: true
          right:
            value:
              simple: Arseny's ransomware project
      - - operator: isEqualString
          left:
            value:
              simple: AttackIQ.TestResult.MasterJob.Id
            iscontext: true
          right:
            value:
              simple: 1c350a5a-84f2-4938-93d8-cc31f0a99482
      - - operator: isEqualString
          left:
            value:
              simple: AttackIQ.TestResult.MasterJob.Assets.ProductName
            iscontext: true
          right:
            value:
              simple: Windows Server 2016 Datacenter
      - - operator: isEqualString
          left:
            value:
              simple: AttackIQ.TestResult.MasterJob.Scenarios.Name
            iscontext: true
          right:
            value:
              simple: Download WannaCry Ransomware Sample
      - - operator: isEqualString
          left:
            value:
              simple: AttackIQ.TestResult.Scenario.Name
            iscontext: true
          right:
            value:
              simple: Download ODCODC Ransomware
      - - operator: isEqualString
          left:
            value:
              simple: AttackIQ.TestResult.Asset.Ipv4Address
            iscontext: true
          right:
            value:
              simple: 172.31.39.254
      - - operator: isEqualString
          left:
            value:
              simple: AttackIQ.TestResult.JobState.Name
            iscontext: true
          right:
            value:
              simple: Finished
      - - operator: isEqualString
          left:
            value:
              simple: AttackIQ.TestResult.Outcome.Name
            iscontext: true
          right:
            value:
              simple: Passed
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: f89bac25-3e76-44b3-8bae-6545a64e17a7
    type: regular
    task:
      id: f89bac25-3e76-44b3-8bae-6545a64e17a7
      version: -1
      name: Get all assessments
      description: Get all assessments in a page or by assessment id.
      script: '|||attackiq-list-assessments'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      assessment_id: {}
      page_number: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: 175052f1-898c-4ed5-84ba-5a0c43fc24bd
    type: title
    task:
      id: 175052f1-898c-4ed5-84ba-5a0c43fc24bd
      version: -1
      name: Untitled Task
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1835,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
