id: Phishing - Simple - Test
version: -1
fromversion: 4.1.0
name: Phishing - Simple - Test
description: A test for the Phishing - Simple playbook.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a156b5b4-d119-495a-8f3d-c82446e2f216
    type: start
    task:
      id: a156b5b4-d119-495a-8f3d-c82446e2f216
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": -190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 215b2b58-1bab-4b78-89c3-bced5e33ac6f
    type: title
    task:
      id: 215b2b58-1bab-4b78-89c3-bced5e33ac6f
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: 234e782b-208d-4d10-8597-202a7716c26a
    type: regular
    task:
      id: 234e782b-208d-4d10-8597-202a7716c26a
      version: -1
      name: PhishingIncident - attachment
      scriptName: PhishingIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      malicious_location:
        simple: attachment
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: b1d47b06-cb0f-4f3c-8b38-82e8b205c0c5
    type: regular
    task:
      id: b1d47b06-cb0f-4f3c-8b38-82e8b205c0c5
      version: -1
      name: Close Manual review
      scriptName: ScheduleCommand
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      command:
        simple: taskComplete id=manual parentPlaybookID=26
      cron:
        simple: '*/1 * * * *'
      endDate: {}
      times:
        simple: "10"
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: a66413f6-914d-4b37-8e42-c27484d4621d
    type: regular
    task:
      id: a66413f6-914d-4b37-8e42-c27484d4621d
      version: -1
      name: Delete context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": -45
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: c5bc731d-17b3-4edd-84bc-209094af5ab2
    type: regular
    task:
      id: c5bc731d-17b3-4edd-84bc-209094af5ab2
      version: -1
      name: Download EML file
      description: Sends http request. Returns the response as json.
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
      - "26"
    scriptarguments:
      body: {}
      filename:
        simple: attachment.eml
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: "yes"
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/Malicious_attachment_simple_phishing2.eml
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 495
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "25":
    id: "25"
    taskid: eefb6e46-41be-434b-8141-63a2619382cc
    type: regular
    task:
      id: eefb6e46-41be-434b-8141-63a2619382cc
      version: -1
      name: minemeld-add-to-miner
      script: '|||minemeld-add-to-miner'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      comment:
        simple: Malicious MD5 for test
      indicator:
        simple: 42914d6d213a20a2684064be5c80ffa9
      miner:
        simple: Malicious
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "26":
    id: "26"
    taskid: 94b22083-6d4b-4bca-82fd-8e0e384d5512
    type: playbook
    task:
      id: 94b22083-6d4b-4bca-82fd-8e0e384d5512
      version: -1
      name: Phishing - Simple
      description: ""
      playbookName: Phishing - Simple
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      GetURLScreenshots:
        simple: "True"
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1150,
        "width": 810,
        "x": 50,
        "y": -190
      }
    }
  }
inputs: []
outputs: []
